version: "3.10"

services:
  neurogengpt:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
      - "1337:1337"
    volumes:
      - ../config.json:/app/config.json
    environment:
      - SUBF=/sub
    env_file:
      - .env
